### ISSUE TITLE
Play nicely with CoffeeScript source maps

### ISSUE THREAD

**Issue by mhart** [mattinsler/longjohn#11]
CoffeeScript now supports source maps - and correct line number mapping with errors.

http://jashkenas.github.com/coffee-script/documentation/docs/coffee-script.html

However, when `longjohn` is `require`'d, it messes with the line mapping (I imagine it's something to do with the override of `Error.prepareStackTrace`).

**Comment by mhart** [comment]
Gonna close this as there hasn't been any action on it in a while

**Comment by zacronos** [comment]
Is lack of action really a sufficient reason to close the issue?  For anyone who starts using longjohn, only to have trouble with coffeescript source maps, being able to search open issues and see that one exists is a useful form of documentation.  Closing the issue artificially hides it.  Or, as I already suggested in an earlier comment, it might be worth noting this issue in the README.

Honestly, I might just open another issue for this and reference this one for the sake of documentation.  I wish it hadn't been closed without feedback.

**Comment by mhart** [comment]
Cool man, go for it – it's been a year and a half without any feedback from @mattinsler, so I'm not really gonna push the issue

**Comment by mattinsler** [comment]
Hey guys, check #51. @drauggres seems to have solved this issue and I integrated it into the codebase.

**Comment by mattinsler** [comment]
Published to npm as version 0.2.9.
