### ISSUE TITLE
Cassé on io.js 1.0.X

### ISSUE THREAD

**Issue by KenanSulayman** [mattinsler/longjohn#35]
Longjohn stopped working on io.js 1.0.X, couldn't investigate any further right now, but we removed longjohn from the dev environment for the time being.

	**/node_modules/longjohn/dist/longjohn.js:185
	        throw e;
	              ^
	ChildProcess.emit (events.js:101:17),
	maybeClose (child_process.js:979:16),
	Socket.<anonymous> (child_process.js:1147:11),
	Socket.emit (events.js:98:17),
	Pipe.close (net.js:456:12)

Any idea?

**Comment by mattinsler** [comment]
Fixed by PR.
