### ISSUE TITLE
Accessing the `err.stack` property crashes your app under certain circumstances

### ISSUE THREAD

**Issue by balupton** [mattinsler/longjohn#36]
See https://github.com/winstonjs/winston/issues/401#issuecomment-61913086 for more info

**Comment by harishanchu** [comment]
Hi foks, 

Same issue here. 
I have used this library along with nodes "domain" to catch errors. After catching error when I try to access the stack property of error object app crashes and displays's partial error stack which is appended by a string "[object Object]" in the console.

My current Node version is v0.12.0
It worked very well with node v0.10.25.

**Comment by mattinsler** [comment]
Fixed by PR.
