### ISSUE TITLE
Doesn't work with node 0.12.

### ISSUE THREAD

**Issue by chevex** [mattinsler/longjohn#37]
## Test script:

```javascript
var longjohn = require('longjohn');
longjohn.async_trace_limit = -1;

function timeoutHandler() {
  console.log('timeout fired!');
  throw new Error('EXPLODE');
}

function createTimeout() {
  setTimeout(timeoutHandler, 1000);
}

createTimeout();
```

## Results:

![image](https://cloud.githubusercontent.com/assets/874394/6739967/34a5c5d2-ce42-11e4-8da0-7c6c5968f77b.png)

![image](https://cloud.githubusercontent.com/assets/874394/6754644/79572bc0-cee3-11e4-969f-c8644e70d6e9.png)

**Comment by db-roberto** [comment]
Having a similar issue

**Comment by lud2k** [comment]
same issue here :(

**Comment by PaulBGD** [comment]
Can confirm :(

**Comment by gobwas** [comment]
+1

**Comment by captscooby** [comment]
Same here.

**Comment by jackquack** [comment]
I have this issue as well. When I log the uncaughtException, this is what I get from a `console.assert(false)` error:

```
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  __cached_trace__: [ {}, {}, {}, {}, {}, {} ] }
```

**Comment by mendlik** [comment]
same here ...

**Comment by drauggres** [comment]
https://github.com/mattinsler/longjohn/pull/41

**Comment by mattinsler** [comment]
Fixed by PR.
