### ISSUE TITLE
0.2.5 Invalid array length

### ISSUE THREAD

**Issue by Trindaz** [mattinsler/longjohn#42]
An example stack trace:

    "RangeError: Invalid array length",
    "    at onwrite (_stream_writable.js:265:15)",
    "    at WritableState.onwrite (_stream_writable.js:96:5)",
    "    at Socket._write (net.js:653:5)",
    "    at doWrite (_stream_writable.js:225:10)",
    "    at writeOrBuffer (_stream_writable.js:215:5)",
    "    at Writable.write (_stream_writable.js:182:11)",
    "    at Socket.write (net.js:615:40)",

But these came up from a few other places too. We solved the problem by reverting to 0.2.2

**Comment by Trindaz** [comment]
I originally posted this as "0.2.5 Breaks on Mac" before having much knowledge of the problem. I believe I found the offending line at https://github.com/mattinsler/longjohn/blob/35a480809bd29ce869a53af85a2dbdd64ce57b55/lib/longjohn.coffee#L99, which attempts to set .length on an array to -1 in cases where it is 0. Fix to come shortly.

**Comment by mattinsler** [comment]
Fixed in version 0.2.6

**Comment by ingo** [comment]
We appear to still be having an issue with 0.2.6, noted here: https://jira.appcelerator.org/browse/CLI-713. We'll see if we can't come up with a test case.

**Comment by mattinsler** [comment]
Please check if this was fixed by v0.2.7.

**Comment by ingo** [comment]
It was, yes, thanks!
