### ISSUE TITLE
Huge CPU usage

### ISSUE THREAD

**Issue by shunanya** [mattinsler/longjohn#46]
I have used Node.js (0.10.33) quite long time with 'longjohn' in the clustered application. No any bad affect of 'longjohn' was detected there. The application worked stable and used about 20% of CPU time.
Recently I have updated my Nodejs engine up to latest version (0.12.5) and correspondingly did update for all dependencies. The 'longjonh' was updated to 0.2.7 version. But, unfortunately, after restart my application began to eat up to 95-100% of CPU time. The commenting of 'var longjohn = require('longjohn');' fixed the situation and now it's using no more than 20% of CPU time.
Can you please explain what is happening? Is it my fault? Or there is some bug?

**Comment by drauggres** [comment]
> it is not recommended to use longjohn in production

Since 0.2.5 (after my [pull request](https://github.com/mattinsler/longjohn/pull/41) was merged), longjohn creates stack trace for EVERY wrapped callback.

**Comment by shunanya** [comment]
I have already sensed this:( 
Besides, it contains the memory leak - the memory usage was grown and grown until I commented the usage of 'longjohn' .

**Comment by jeffcharles** [comment]
My team ran into the same issue while using longjohn during automated tests on Node v0.10.38. v0.2.4 works great, v0.2.7 causes a bunch of our tests to timeout. An example being a test that took 119 ms on v0.2.4 now takes 1580 ms on v0.2.7.

**Comment by drauggres** [comment]
@jeffcharles, @shunanya, please, check with [this](https://github.com/drauggres/longjohn).

**Comment by jeffcharles** [comment]
That seems to perform much better. Test times are back to what they were on v0.2.4.

**Comment by mattinsler** [comment]
Hey Sergey. Could you send me an email? I'd love to chat about giving you
commit/push creds on longjohn.

**Comment by drauggres** [comment]
@mattinsler, thank you for your trust. This PR is last, so there is no need in commit/push creds for me.

**Comment by mattinsler** [comment]
OK, sounds good.

**Comment by shunanya** [comment]
Hey Sergey. Good job. 
Since you already upgraded the code, could you please change correspondingly the version number in the package.json so that longjohn can be updated automatically?

**Comment by drauggres** [comment]
@shunanya, done.
