### ISSUE TITLE
[question] Advantages over `Error.stackTraceLimit`

### ISSUE THREAD

**Issue by wearhere** [mattinsler/longjohn#64]
Hi, simple question—what does this library do that setting [`Error.stackTraceLimit`](https://nodejs.org/api/errors.html#errors_error_stacktracelimit)` = <number greater than 10, the default>` does not?

A [cursory Internet search](http://stackoverflow.com/a/10419288) suggests that Longjohn collects async stack traces whereas `Error.stackTraceLimit` does not, but [here](https://github.com/meteor/meteor/blob/devel/tools/cli/main.js#L23) is an example of `Error.stackTraceLimit` theoretically collecting stack traces across [fiber](https://github.com/laverdet/node-fibers) calls, which are asynchronous.

Also do you know if perhaps `Error.stackTraceLimit` is more suitable for [production use](https://github.com/mattinsler/longjohn#production-use) than longjohn? (Since we use fibers, so if `Error.stackTraceLimit` works for that, that would be good even if it didn't work in other circumstances where longjohn did work.)

**Comment by mattinsler** [comment]
I don't think that you need longjohn when using node-fiber. Fiber pretty much removes the async callback stack truncation issue by default. I'd say you should just not use longjohn if you're using fiber.
